# Generated by Django 4.1.6 on 2023-02-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_img_opis_img_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='autor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
