# Generated by Django 4.1.6 on 2023-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_img_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='autor',
        ),
    ]
